ifl0w/RandomWallpaperGnome3

randomwallpaper@iflow.space/sourceAdapter.js
The Wallhaven wallpaper source is broken since Saturday, May 25th. 
So I decided to check a bit further, as your extension is well documented and well-structured, I was able to display and add logs and so debug the issue. I hope this will help other people.
=> fix Wallhaven adapter due to recent changes of wallhaven.cc

randomwallpaper@iflow.space/elements.js, randomwallpaper@iflow.space/wallpaperController.js
As I mentioned in #72 the call to `Gio.file_new_for_uri` fails starting in 3.34 as only the `file://` protocol is supported.
For this reason I used the `Soup` HTTP client to download the files and save them on the file system.
I tried it on my Fedora 31 installation and I can now download new wallpapers without the `setcap` call.
Secondly, it seems that the GTK inheritance mechanism became stricter in 3.34 and you have to use `GObject.registerClass` to inherit from GTK components.
Fixes #72 .
=> Use gi.Soup to download files to fix extension in Gnome 3.34, also use proper inheritance

randomwallpaper@iflow.space/elements.js
Updated to work with the latest GNOME shell (3.38.0), and simplified the code using clutter animations.
=> Migrate from tweens to clutter animations (fixes #92)

randomwallpaper@iflow.space/wallpaperController.js, randomwallpaper@iflow.space/wallpapers/.gitignore
A gnome shell extension could be installed using the distribution package system. In this case, the wallpaper download directory will be under `/usr/share/gnome-shell/extensions` and fetching wallpapers will fail due to permissions error.
This PR brings the usage of $XDG_CACHE_HOME environment variable to set the download directory location: `$XDG_CACHE_HOME/RandomWallpaperGnome3/wallpapers` or if not present `$HOME/.cache/RandomWallpaperGnome3/wallpapers`.
=> XDG_CACHE_HOME used for downloading wallpapers

.gitmodules, container/Dockerfile, container/README.md, container/runx11docker.sh
To make developing for different GNOME versions (especially backporting) easier, add containers which allow you to start a Docker container containing a different GNOME version.
This eliminates the use of virtual machines. It also mounts the extension in the container so you can develop outside the container and just refresh GNOME inside the container to test the changes. Each image is only about 700 MB in size (for now), so it's also relatively small compared to a virtual machine.
Just pitching the idea, can of course be implemented differently. Also limited to GNOME 36 and 38 for now.
=> Add development containers for different GNOME versions

randomwallpaper@iflow.space/metadata.json
Confirmed working on Gnome 41 by disabling extension version checks using `gsettings set org.gnome.shell disable-extension-version-validation "true"` and running the current, latest version of this extension provided at https://extensions.gnome.org/extension/1040/random-wallpaper/
=> Support Gnome 41

randomwallpaper@iflow.space/soupBowl.js
If libsoup is already loaded, the import doesn't fail because it isn't executed. However because it is already loaded, we can check which version we are currently running.
This is just a theory however! **It needs to be confirmed on both a libsoup3-only system and a combined system if it doesn't cause any regression on libsoup3 systems.**
Fixes #123
=> Fix wrong libsoup version when already loaded

.gitmodules, container/Dockerfile, container/README.md, container/runx11docker.sh
Add development containers used in the 'gnome-shell-legacy' branch (#110) to the develop branch as well. Requested in https://github.com/ifl0w/RandomWallpaperGnome3/issues/123#issuecomment-996662199.
=> Add development containers to develop branch

randomwallpaper@iflow.space/metadata.json
=> Add GNOME 43 to supported shell-version

README.md, randomwallpaper@iflow.space/prefs.js, randomwallpaper@iflow.space/schemas/org.gnome.shell.extensions.space.iflow.randomwallpaper.gschema.xml, randomwallpaper@iflow.space/settings.js, randomwallpaper@iflow.space/sourceAdapter.js, randomwallpaper@iflow.space/ui/generic_json.blp, randomwallpaper@iflow.space/ui/generic_json.js, randomwallpaper@iflow.space/ui/page_sources.blp, randomwallpaper@iflow.space/ui/reddit.blp, randomwallpaper@iflow.space/ui/reddit.js, randomwallpaper@iflow.space/ui/source_row.blp, randomwallpaper@iflow.space/ui/source_row.js, randomwallpaper@iflow.space/ui/unsplash.blp, randomwallpaper@iflow.space/ui/unsplash.js, randomwallpaper@iflow.space/ui/wallhaven.blp, randomwallpaper@iflow.space/ui/wallhaven.js, randomwallpaper@iflow.space/wallpaperController.js
Multiple sources are now possible and randomly selected. A hidden feature is that the list gets sorted by source type on opening the preferences window.
They're stored each in its own gsettings. Timestamps as IDs remembered for mapping in `/sources`, general settings in `/sources/general/` and specific settings in the respective source subfolders `/sources/${Source}/`.
I'm not sure if I introduced the bug through the rework above, but the timer wasn't starting again after closing the preferences window. ~~This was fixed in e7aa0c4.~~ I'm experiencing that the timer resets after some time.
It seems the cause is that the extension runs in two contexts which can't be caught by the instance/singleton workaround. This might be the same issue behind #135 - there are basically multiple timers …
=> Multiple Sources (Requires #143)

randomwallpaper@iflow.space/prefs.js, randomwallpaper@iflow.space/schemas/org.gnome.shell.extensions.space.iflow.randomwallpaper.gschema.xml, randomwallpaper@iflow.space/sourceAdapter.js, randomwallpaper@iflow.space/wallpaperController.js
I've decoupled the preferences window from all background activity. The background controller now tracks some gsetting changes to communicate with the preferences window. I'm confident this fixes #135 since there's now only one single `wallpaperController` running.
This also fixes #126 - just use your favorite keyboard shortcut manager (like gnomes in settings -> keyboard -> shortcuts -> own shortcuts) to set the variable `request-new-wallpaper` to `true`:
~~~
gsettings --schemadir "${XDG_DATA_HOME:-$HOME/.local/share}/gnome-shell/extensions/randomwallpaper@iflow.space/schemas" set org.gnome.shell.extensions.space.iflow.randomwallpaper.backend-connection request-new-wallpaper true
~~~
=> Decouple preference window from wallpaperController (Requires #141)

randomwallpaper@iflow.space/adapter/genericJson.js, randomwallpaper@iflow.space/adapter/localFolder.js, randomwallpaper@iflow.space/adapter/reddit.js, randomwallpaper@iflow.space/adapter/unsplash.js, randomwallpaper@iflow.space/adapter/urlSource.js, randomwallpaper@iflow.space/adapter/wallhaven.js, randomwallpaper@iflow.space/elements.js, randomwallpaper@iflow.space/prefs.js, randomwallpaper@iflow.space/schemas/org.gnome.shell.extensions.space.iflow.randomwallpaper.gschema.xml, randomwallpaper@iflow.space/ui/genericJson.js, randomwallpaper@iflow.space/ui/localFolder.js, randomwallpaper@iflow.space/ui/pageGeneral.blp, randomwallpaper@iflow.space/ui/reddit.js, randomwallpaper@iflow.space/ui/sourceRow.js, randomwallpaper@iflow.space/ui/unsplash.js, randomwallpaper@iflow.space/ui/urlSource.js, randomwallpaper@iflow.space/ui/wallhaven.js, randomwallpaper@iflow.space/wallpaperController.js
It's now possible to define a command that will run after setting a wallpaper.
This is particular interesting as [Gradience](https://github.com/GradienceTeam/Gradience) is currently implementing a CLI-Interface which can color GTK4/Libadwaita themes based on an image. `gradience monet %wallpaper_path%`
This fixes #128 
* https://github.com/GradienceTeam/Gradience/pull/675
* https://github.com/GradienceTeam/Gradience/issues/671
=> Allow running post commands (Requires #147)

randomwallpaper@iflow.space/adapter/baseAdapter.js, randomwallpaper@iflow.space/adapter/genericJson.js, randomwallpaper@iflow.space/adapter/localFolder.js, randomwallpaper@iflow.space/adapter/reddit.js, randomwallpaper@iflow.space/adapter/unsplash.js, randomwallpaper@iflow.space/adapter/urlSource.js, randomwallpaper@iflow.space/adapter/wallhaven.js, randomwallpaper@iflow.space/elements.js, randomwallpaper@iflow.space/history.js, randomwallpaper@iflow.space/prefs.js, randomwallpaper@iflow.space/schemas/org.gnome.shell.extensions.space.iflow.randomwallpaper.gschema.xml, randomwallpaper@iflow.space/ui/sourceRow.blp, randomwallpaper@iflow.space/ui/sourceRow.js, randomwallpaper@iflow.space/wallpaperController.js
Blocking images is now possible. Blocking happens on filename matches. If an image is blocked another try is given - up to 5 times. Blocking is individual for every configured source. ~~There's currently no UI for unblocking images. To unblock an image remove the string from the array at `/org/gnome/shell/extensions/space-iflow-randomwallpaper/sources/general/${ID}/blocked-images` with dconf.~~
This fixes #139
=> Allow blocking images (Requires #148)

randomwallpaper@iflow.space/adapter/genericJson.js, randomwallpaper@iflow.space/adapter/wallhaven.js, randomwallpaper@iflow.space/history.js, randomwallpaper@iflow.space/hydraPaper.js, randomwallpaper@iflow.space/jsonpath/jsonpath.js, randomwallpaper@iflow.space/prefs.js, randomwallpaper@iflow.space/schemas/org.gnome.shell.extensions.space.iflow.randomwallpaper.gschema.xml, randomwallpaper@iflow.space/ui/pageGeneral.blp, randomwallpaper@iflow.space/ui/sourceRow.js, randomwallpaper@iflow.space/utils.js, randomwallpaper@iflow.space/wallpaperController.js
If available and activated [HydraPaper](https://gitlab.gnome.org/GabMus/HydraPaper) can now be used to populate multiple displays.
This also works together with `hydrapaperd`, the daemon which tracks monitor changes: `systemctl enable --now --user org.gabmus.hyperpaperd.service`
Fixes #117 
---
Only the lock screen can be changed now.
Fix #74 and partially #70
=> Hydrapaper and separate lock screen wallpaper (Requires #152)

src/historyMenuElements.ts
Following the G45+ guidelines:
https://gjs.guide/extensions/review-guidelines/review-guidelines.html#gtk-and-gdk-imports
=> Remove Gtk import in shell context

build.sh, src/adapter/unsplash.ts, src/extension.ts, src/historyMenuElements.ts, src/logger.ts, src/metadata.json, src/notifications.ts, src/prefs.ts, src/randomWallpaperMenu.ts, src/settings.ts, src/ui/genericJson.ts, src/ui/localFolder.ts, src/ui/reddit.ts, src/ui/sourceRow.ts, src/ui/unsplash.ts, src/ui/urlSource.ts, src/ui/wallhaven.ts, src/wallpaperController.ts, tsconfig.json, types/gtk4/adw/index.d.ts, types/misc/index.d.ts, types/ui/index.d.ts, types/ui/main.d.ts, types/ui/panelMenu.d.ts, types/ui/popupMenu.d.ts
This implements the remaining bits and pieces needed for Gnome45+. In turn, it will make this extension incompatible with Gnome < 45.
Luckily in my previous road to v3 I separated both contexts (background shell/foreground preference window) which is way more implied than before. Both contexts use separate import statements which fail for the other context.
The only module left we're using by both contexts is the settings module. For this to work I had to drag the current contexts' extension import to the settings module.
I'm not sure about the deduplication of both prefs classes. It's making us drag all variables as function parameter because we can't use the constructor anymore. (ec5b0c7b5fc9c8bdafd8de43fe119d9abd7061c0)
fix #172 
fix #177
=> Support Gnome45

src/historyMenuElements.ts, src/prefs.ts, src/randomWallpaperMenu.ts, src/ui/genericJson.ts, src/ui/localFolder.ts, src/ui/reddit.ts, src/ui/sourceRow.ts, src/ui/unsplash.ts, src/ui/urlSource.ts, src/ui/wallhaven.ts
This removes the remaining const classes which were needed for `GObject.registerClass()` before.
The same can be achieved with the yet undocumented static class features of GObject: https://gitlab.gnome.org/ewlsh/gjs-guide/-/issues/72
Unfortunately the *generated code* has a quirk not liked by eslint and triggers the rule [`no-unused-expressions`](https://eslint.org/docs/latest/rules/no-unused-expressions) and I'm not sure why. I've disabled the rule for the affected files for now.
~~~ js
var _a, _b, _c, _d;
…
// The following line produces the linting error
_a = GenericJsonSettingsGroup, _b = GObject.GTypeName, _c = Gtk.template, _d = Gtk.internalChildren;
…
(() => {
GObject.registerClass(_a);
})();
~~~
=> Remove remaining const classes

src/soupBowl.ts
While testing my various configured sources for the initial genericjson improvements again, I stumbled upon a source which doesn't work for the default `Mozilla/5.0` User-Agent. The site is protected by Cloudflare and I assume that the User-Agent `Mozilla/5.0` lets Cloudflare believe that JavaScript should be available and tries to test it with an anti bot challenge.
Using a different string as the User-Agent goes around this test - I only tested this with `RandomWallpaperGnome3/3.0`.
~~~
Failing:
$ http "https://danbooru.donmai.us/posts.json?tags=rating:general" User-Agent:Mozilla/5.0
Working:
$ http "https://danbooru.donmai.us/posts.json?tags=rating:general" User-Agent:RandomWallpaperGnome3/3.0
~~~
As a first thought I added a simple input to the configuration which lets the user …
=> Change default User-Agent to `RandomWallpaperGnome3/3.0`

src/history.ts, src/historyMenuElements.ts, src/randomWallpaperMenu.ts, src/stylesheet.css, src/wallpaperController.ts
Change how images are previewed in the popup menu.
=> Single preview widget for all history elements

src/ui/pageGeneral.blp
It's possible to fetch new ones for quite some while now. Fill from history is only used as fallback and when setting a specific wallpaper from history.
=> Remove description of legacy limitation

src/soupBowl.ts
When soup fails making the request, the promise never resolves. This adds a rejection of the promise by default.
=> Fix request error handling with explicit rejection
